const kLongPressDurationMilliseconds = 1200;
const kBorderRadius = 12.0;
const kHomePageLineWidth = 0.70;
const kHomePageLineThickness = 2.0;
const kStartButtonIconSize = 70.0;
const kStartButtonRadius = 0.40;
const kHomePageSmallIcon = 18.0;
const kSessionTimerStrokeWidth = 16.0;
const kSettingsImageHeight = 0.25;
const kSettingsHorizontalPageIndent = 0.09;
const kAudioFadeDuration = 3500;
const kChartAnimationDuration = 500;
const kPageIndentation = 0.03;
const kChartAxisFontSize = 10.0;
const kClocksHeight = 0.25;
const kChartBarLineWidth = 2.0;
const kChartLabelsFontSize = 10.0;
const kNoOfXLabelsOnLineChart = 5;
const kFadeInTimeMilliseconds = 500;
const kHomePageAnimationDuration = 400;
const kAppName = 'Zense Meditation Timer';
const kOnTimeUpOnlyText = 'on time up only';
const kNoBarChartDataMsg = 'No meditation stats to display yet...';
const kNoChartDataMsg = 'No meditation stats to display yet...';
const kNoMeditationHistoryMsg = 'No meditation history to display yet...';
const kSessionWillBeginShortly = "Your session will begin shortly...";
const kSetFixedTimeGreaterThanZero =
    'Set fixed time to greater than zero';

